# Generated by Django 3.2.7 on 2021-09-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('info', models.CharField(max_length=500, verbose_name='Info')),
                ('cover', models.ImageField(upload_to='cover', verbose_name='Cover')),
                ('book_pdf', models.FileField(upload_to='book_pdf', verbose_name='Book_PDF')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='DateTime')),
            ],
        ),
    ]
